services:
  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root123@
      MYSQL_DATABASE: chat_app
      mysql_user: user1
      mysql_password: user123@
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat_network
  
  neo4j:
    image: neo4j:5
    container_name: chat-neo4j
    ports:
      - "7474:7474"   
      - "7687:7687"  
    environment:
      NEO4J_AUTH: neo4j/toszqQp8nCvUsOAkCSwcf3CKYoFmfmjLE1R0CeEq0ZQ
    volumes:
      - neo4j_data:/data
    networks:
      - chat_network

  backend:
    build: ./backend
    container_name: chat-backend
    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://user1:user123%40@mysql:3306/chat_app
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: toszqQp8nCvUsOAkCSwcf3CKYoFmfmjLE1R0CeEq0ZQ
      JWT_SECRET_KEY: supersecretkey
      JWT_ALGORITHM: HS256
      JWT_EXPIRE_MINUTES: 60
    networks:
      - chat_network
  frontend:
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge

volumes:
  mysql_data:
  neo4j_data: